version: 0.0
os: linux
files:
  - source: /
    destination: /medongaule/deploy
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/pre-deploy.sh
      timeout: 720
      runas: ec2-user
    - location: scripts/deploy.sh
      timeout: 720
      runas: ec2-user
