name: production-cicd
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  ci:
    name: Packaging
    uses: ./.github/workflows/ci.yaml
    with:
      version: ${{ github.sha }}
      php-image-tag: 8.3.9-fpm-bookworm
      target-env: production
      devops-bucket-name: ${{ vars.APPNAME }}-production-devops-bucket
    secrets: 
      AWS_ACCOUNT: ${{ secrets.MDALE_AWS_ACCOUNT }}
  cd:
    name: Deploy
    needs: ci
    uses: ./.github/workflows/cd.yaml
    with:
      version: ${{ github.sha }}
      target-env: production
      devops-bucket-name: ${{ vars.APPNAME }}-production-devops-bucket
    secrets: 
      AWS_ACCOUNT: ${{ secrets.MDALE_AWS_ACCOUNT }}
