name: stage-cicd
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  ci:
    name: Packaging
    uses: ./.github/workflows/ci.yaml
    with:
      version: ${{ github.sha }}
      php-image-tag: 8.3.9-fpm-bookworm
      target-env: stage
      devops-bucket-name: ${{ vars.APPNAME }}-stage-devops-bucket
    secrets: inherit
  cd:
    name: Deploy
    needs: ci
    uses: ./.github/workflows/cd.yaml
    with:
      version: ${{ github.sha }}
      target-env: stage
      devops-bucket-name: ${{ vars.APPNAME }}-stage-devops-bucket
    secrets: inherit
